spring:
  datasource:
    url: jdbc:mysql://localhost:3306/evoting?createDatabaseIfNotExist=true
    username: root
    password: Vikas@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update

  output:
    ansi:
      enabled: always